runtime: nodejs22

instance_class: F2  # puedes ajustar según tus necesidades

env_variables:
  DB_USER: leones-db
  DB_PASSWORD: root
  DB_NAME: leones_calistenia
  DB_HOST: leones-calistenia-470802:us-west1:leones-db